@startuml classes

diamond InputFrame
diamond OutputFrame

package UserInput {
    class UserInput {
        + Ignition ignition
        + Gear gear
        + Pedal throttle
        + Pedal brake
        + Blinker blinker
        + SetIgnition()
        + SetGear()
        + SetThrottle()
        + SetBrake()
        + SetBlinker()
    }
    class SendInputMessage {
        + PopulateFrame()
        + SendFrame()
    }
    SendInputMessage -up-> UserInput
}

package Server {
    class Inputs {
        + GetAcceleratorPedal()
        + GetBrakePedal()
        + GetRequestedGear()
    }
    class SendOutputMessage {
        + PopulateFrame()
        + SendFrame()
    }
    class Engine {
        + EngineSpeed
        + RequestTorque()
        - CalculateTorque()
    }
    class Transmission {
        - GearRatioMap
        + GetGearRatio()
    }
}

package Dashboard {
    class Speedometer {
        - CurrentSpeed
        + DisplaySpeed()
    }
    class Tachometer {
        - CurrentRpm
        + DisplayRpm()
    }
    class GearIndicator {
        - CurrentGear
        + DisplayGear()
    }
}

SendInputMessage --> InputFrame
InputFrame --> Inputs
Inputs --> Engine
Inputs --> Transmission
Engine --> SendOutputMessage
Transmission --> SendOutputMessage
SendOutputMessage --> OutputFrame
OutputFrame --> Speedometer
OutputFrame --> Tachometer
OutputFrame --> GearIndicator

@enduml
