@startuml Swdesign
left to right direction

package "User Input" {
  [CANTransmitter]
}

package "DriveLine Emulator" {
[CANReceiver]
[Server]
package DriveLine{

[Server] ->  [Engine]
[Server] -> [Gearbox]
[Server] -> [Wheel] 
[Server] <-> [State]
}
[CANSender]
}

package "Display" {
  [display]
}
[CANTransmitter] --> [CANReceiver] : CAN0
[CANReceiver] --> [Server]
[Server] -->[CANSender]
[CANSender] --> [display] : CAN1

@enduml
