@startuml Swdesign
left to right direction

package "User Input" {
  [Keyboard] --> [CANTransmitter]
}

package "DriveLine" {
  [CANTransiever]
  [Server]
  [Server] <-> [Driveline Simulator]
}

package "Display" {
  [CANReciever]
  [display]
}

[CANTransmitter] --> [CANTransiever] : vcan0
[CANTransiever] <-> [Server]
[CANTransiever] --> [CANReciever] : vcan0
[CANReciever] --> [display]

@enduml
